version: "{build}"
platform: x64
environment:
  matrix:
    - PYTHON: "C:\\Python37"
      ARCH: "32"
    - PYTHON: "C:\\Python37-x64"
      ARCH: "64"
install:
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\Scripts\\pip install pyinstaller"
  - ps: Set-Content "balance_check\\version.py" ( "__version__ = '{0}'" -f ( git describe --tags --always ) )
  - "%PYTHON%\\Scripts\\pip install -e ."
  - "%PYTHON%\\Scripts\\pyinstaller balance-check.spec"
  - ps: |
      $env:ARCHIVE_VERSION = $env:APPVEYOR_REPO_COMMIT.Substring(0, 8)
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          # Building a tag
          $env:ARCHIVE_VERSION = $env:APPVEYOR_REPO_TAG_NAME
      }
      7z a dist\balance-check-$env:ARCHIVE_VERSION-win$env:ARCH.zip dist\balance-check.exe
build: off
artifacts:
  - path: "dist\\balance-check*.zip"
deploy:
  provider: GitHub
  artifact: /.*\.zip/
  force_update: true
  auth_token:
    secure: cQFP/T5Dnyh3SwHoRFsK23P2gyXa5j+ROCMuq4x2nIU5bycGRZO4snTmwX5CJ1pP
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

